### ISSUE TITLE
Download Log problems on some Chromium versions

### ISSUE THREAD

**Issue by LGraemeG** [Linaro/mr-provisioner#43]
Chromium Version 60.0.3112.78 (Developer Build) (64-bit)

Download log onto leads to blank page, AdBlocker  is disabled for mr-provisioner URLs.

Same procedure leads to log being displayed on Firefox.

This seems new for the new version of Chromium as it was previously working.

**Comment by rengolin** [comment]
Chromium 61.0.3163.79 (Developer Build) (64-bit), also broken.

**Comment by rengolin** [comment]
On same system (Arch), firefox-55.0.3-1 works.

**Comment by bwalex** [comment]
This is the relevant change in Chromium/Chrome: https://bugs.chromium.org/p/chromium/issues/detail?id=684011&desc=2

We could add the data URL into the href of the button, but that means (A) rerendering the button on every character pulled from the console and (B) a really large href in the DOM.

A possible workaround might be to set the contents of the new window with a setTimeout(..., 0) or so just after opening it - but I don't know if that works in practice or it's also somehow blocked.

**Comment by rengolin** [comment]
AFAICR, there's a limit for GET data (4k?), so even doing that would only get you so much.

Honestly, I can see why Chromium would want to not let people save temporary data that passes through a web page into some DOM object, so anything we try to hack will likely lose support in the future.

How does Packet/Scalaway do? They have console functionality on their cloud offerings (not quite the same, but...).

Would a browser add-on be too complicated?

**Comment by bwalex** [comment]
What do you mean a limit for GET data? There certainly is not, and just about every file download you've ever done was an HTTP GET request.

Also, the chromium change is about avoiding URLs that look dodgy, not about writing arbitrary content to a page - which is quite obvious, really, since writing arbitrary content to a page is what every single SPA does. Similarly, what you call, "temporary data that passes through a web page into some DOM object" is not hacky at all, that's again what every single SPA does.

`window.open().document.write('...');` seems to work just fine, so we should just give that a go for now.

A browser add-on is just the wrong solution.

**Comment by bwalex** [comment]
Alternatively, there's also react-popout to help with that.

**Comment by rengolin** [comment]
I meant the GET request itself. While there isn't an upper limit in the RFC, every browser/server has a limit for GET (which is usually a few K).

**Comment by bwalex** [comment]
You do realize that there is not GET request involved in retrieving the machine log in the first place, right?

Also, the usual URL/request limit does clearly not apply to data URLs, that'd kinda defeat the purpose. Data URL limits are browser specific, but are pretty consistently in the several MB at least.

**Comment by rengolin** [comment]
I have no idea how Mr-p works, nor am I current with recent JS libraries (last I did anything around that was 2003), so I honestly don't realise anything. I was just trying to be helpful. Seems that's not needed around here. cheers!
